# Generated by Django 5.1.2 on 2024-10-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
